[project]
name = "chip-simulation"
version = "0.1.0"
description = "Agent based model of CHIP and methylation heterogeneity"
readme = "README.md"
requires-python = "==3.13.*"
dependencies = [
    "memory-profiler>=0.61.0",
    "mesa[rec]>=3.5.0",
    "scipy>=1.17.1",
    "seaborn>=0.13.2",
]

[dependency-groups]
dev = [
    "ruff>=0.15.5",
]
